### ISSUE TITLE
make python 2 and 3 compatible

### ISSUE THREAD

**Issue by benbowen** [biorack/omaat#1]
Since people will be using this code for a long time, I want to go ahead and make it 2 and 3 cros-compatible.  

This generally means writing it for Python 3 and making reverse imports that allow it to work in 2.7.

I created a new .ipy file so it doesn't mess up our production version.  Its mainly print statements and string decoding.  Feel free to occasionally hack away at this.  

I'm testing with a dual environment setup this way:
http://conda.pydata.org/docs/py2or3.html

**Comment by aitatanit** [comment]
Will do

**Comment by benbowen** [comment]
@aitatanit, this is actually not a metatlas project, but feel free to help out with it. :) 
These arrayed analysis tools are mainly written by @tderond and me with help from @raad0102.

**Comment by tderond** [comment]
hopefully will take a crack at it tomorrow.

Tristan ⋈

**Comment by benbowen** [comment]
@tderond I regretfully made a copy of the .ipy file, but the "git" way would have been to make a branch to develop for this issue.

**Comment by tderond** [comment]
ran the [futurize](http://python-future.org/futurize.html) script on the code (needed to take out the ipython "magic" first, because the futurize script didnt like that), which generated [this diff](https://github.com/biorack/OpenMSI_Arrayed_Analysis_Tools/files/322458/futurize_diff.txt). hopefully after i apply all those changes to the code, it'll be cross-compatible.

**Comment by tderond** [comment]
I ended up applying most of the changes in the diff file, except for:
-replacing input() by eval(input()). I noticed @oruebel had already replaced input() by raw_input(), but instead using "from builtins import input" is cross-compatible)
-python2-style division. Hopefully python3 division (which is always floating point) will fix the rounding error @raad0102 brought up.

testing now before I commit

**Comment by tderond** [comment]
Alright it works in both python 2 and 3 for me. please help beta-best.

**Comment by raad0102** [comment]
I just pulled the new code and tried to run it using Python 2.7 but got this error in the first cell
![screen shot 2016-06-20 at 11 03 20 am](https://cloud.githubusercontent.com/assets/10214084/16205054/c13889dc-36d6-11e6-8e01-8e8908378caf.png)

**Comment by oruebel** [comment]
Note, there is a future builtins module for this:

https://docs.python.org/2/library/future_builtins.html

**Comment by tderond** [comment]
Oliver, do you mean I should have used a different package for the builtins?

Tristan ⋈

**Comment by oruebel** [comment]
You could do something like this:

import sys
if sys.version_info >= (3,):
   from builtins import zip
   from builtins import chr
   from builtins import str
else:
   from **builtin** import zip
   from **builtin** import chr
   from **builtin** import str

Alternatively you could also use the future package:

https://pypi.python.org/pypi/future

which might make things a bit easier but requires you to have an additional
library.

Cheers,

Oliver

**Comment by tderond** [comment]
I'm just confused because this code worked fine on Python 2 on my computer.
so I must have the python 2 package "builtins" installed.
Now, does requiring people to have "builtins" installed cause more trouble
than requireing them to have both "future" and "builtins"  installed?

I don't think the **builtin** package contains the functions i'm trying to
import, and those it does contain i dont think have python3 behavior.

This hurts my head why do all these packages have almost the same name

Tristan ⋈

**Comment by tderond** [comment]
Apparently both "future" and "builtins" are in the package "future", so
there's no reason to use one and not the other.
I don't think there's a way around wanting cross-compatible code without
the "future" package.

So, @raad0102, could you please try installing the "future" package ("conda
install future") and try running again?

Tristan ⋈

**Comment by raad0102** [comment]
After installing future, it now runs

**Comment by oruebel** [comment]
Just to clarify, the builtins module under Python 3 and the **builtin** (no
s) module in Python 2 should be the same. The **builtin** module was
renamed in Python 3 to builtins to avoid the confusion that exists in
Python 2 between **builtin** and **builtins** (with and without s, both
exists in Python 2 and have slightly different meaning). However, the way
the notebook works right now, it seems that you actually need to have the
builtins module for things to work. Somehow, there seems to be a collision
in the iPython kernel when you call the input function when you use the
default. My guess is that probably the ipywidgets overwrite the input
function. I don't think that requiring the future module should be a big
problem so I would just go with that.

Just for my own understanding, why do you need to import the function from
builtin explicitly here?

Cheers,

Oliver

**Comment by tderond** [comment]
The short answer is: because "futurize" told me to import those builtins

The long answer: some builtins have different meanings in python2 vs python3. the builtin module allows you to use python3 behaviour in python2, which makes it cross-compatible. (http://python-future.org/imports.html)

I'm gonna look into the "input" issue tomorrow hopefully. I think you're right that ipython/jupyer overwrites the input and raw_input functions (to allow them to ask for input in the notebook rather than in the terminal). Does this actually affect the way the notebook runs right now?

**Comment by oruebel** [comment]
When you use the builtins module everything seems to work fine. However,
when I tried to use Python 2 version of the functions, then things crashed.
If you require the future package and use builtins it seems like things
work fine.

Cheers,

Oliver
