### ISSUE TITLE
writeResultTable(…)  reuse of iterator variable in nested loops

### ISSUE THREAD

**Issue by oruebel** [biorack/omaat#4]
The writeResultTable(…) function function contains the following nested loop:

for i,myPixel in enumerate(spotList): #how many spots
          ...
     for i,ion in enumerate(self.ions): #how many ions
                   ....
The variable “i” is used as an index in both loops, i.e., the inner loop will overwrite the value of i from the outer loop. Since the value of "i" is accessed in both the inner and outer loop, this very quickly leads to problems.

**Comment by tderond** [comment]
as far as i can tell this hasn't actually caused any errors yet because the outer loop only used the outer "i" and the inner loop only used the inner one. The way python does for loops it doesn't actually use the variables to keep track of loop count.
Anyways, still fixing this to make sure it doesnt cause errors int he future

**Comment by tderond** [comment]
variable "j" in the 3rd level down wasnt being used, so took out enumerate() there and turned the "i" of the 2nd level into a "j"
