### ISSUE TITLE
Spot optimization fails on spots with 0 intensities

### ISSUE THREAD

**Issue by oruebel** [biorack/omaat#6]
It would be good if 

optimizeSpots_with_dialogs()

would not raise a SpotOptimizationException when a spot cannot be optimized (e.g., when the spectra all 0 under the spot). Instead those spots should just remain unchanged, or a simple warning should be printed rather than making the optimization appear as failed.

**Comment by tderond** [comment]
This would be super easy to fix. As you can see there's only one place where SpotOptimizationException is raised, and it's stipulated on best<=0. I figured if it's 0 there has got to be something weird going on because real data (in my experience) never has 0's, but apparently you have data that does?

Then there is the question, if a spot cannot be moved because everywhere it goes it's too close to another spot (I call this a spot being "checkmate"), should that still raise the exception?

**Comment by oruebel** [comment]
I would simply change it to <0. Some of the datasets (e.g., lung dataset)
have a masked applied where the background around the sample are either set
to 0 or have not been recorded. While the masked datasets we currently have
are not spotted samples, I'm sure some reviewer is going to run OMAAT on a
random dataset even if it not a spotted sample.

**Comment by tderond** [comment]
I think this is fixed now. Give it a try and let me know if it still needs work
